### ISSUE TITLE
Flutter 3.16 breaking changes

### ISSUE THREAD

**Issue by suragch** [suragch/mongol#47]
Flutter 3.16 breaks the following files:

- [x] mongol_text_painter.dart (textScaleFactor)
- [x] mongol_text_selection.dart (gesture detection event details)
- [x] mongol_input_decorator.dart (InputDecoration)

**Comment by Satsrag** [comment]
@suragch Are you solving this now? If not, I will try it this week.

**Comment by suragch** [comment]
@Satsrag I started working on it. Give me a few more days. It was a bigger job than I expected at first.

**Comment by Satsrag** [comment]
👌thank you

**Comment by suragch** [comment]
@Satsrag I've pushed the changes of the things I've been working on. The compile time errors are gone. Unfortunately, I broke everything at runtime. 😭 

The rest of this week I am going to be busy with other things. If you have time, you can take a look at it. Or if it is easier, you can start at the last good commit and try your own approach.

**Comment by Satsrag** [comment]
👌Yes, I will try it.

**Comment by Satsrag** [comment]
The text field seems working now. Please review [this](https://github.com/suragch/mongol/compare/11c4f2d490bafcb334c76658013fd3fcc09f0044...master). However, the previous issues still exist.

**Comment by suragch** [comment]
@Satsrag Nice! Thanks for fixing the crash!

There are a couple more problems I think we should fix before publishing, though. One is that MongolText resizes to get smaller but it doesn't resize to get larger. You can see this in the following animation:

![mongol_text](https://github.com/suragch/mongol/assets/10300220/0b80e315-8e04-4cc6-be02-930dca9fc04c)

Also the line spacing has changed. This is the old one:

![image](https://github.com/suragch/mongol/assets/10300220/e440757b-1056-4093-82ed-0b563160cd11)

But this is the current one:

<img width="502" alt="Screenshot 2023-12-18 at 10 45 17" src="https://github.com/suragch/mongol/assets/10300220/fa3ed1ee-b027-4bf1-9860-78551beaf053">

If you can work on it let me know. Otherwise I should have time to work on it this week.

**Comment by Satsrag** [comment]
I may not have time this week. There should be time on weekends. You can work on it if you have time. If some work remains until the weekend, I will have a try.

**Comment by suragch** [comment]
Ok, great. I'll see what I can do during the week and pass it to you this weekend if I don't finish before then.

**Comment by suragch** [comment]
Well, I didn't find the problems, but I added another example to the demo app called MongolTextPainter:

<img width="438" alt="Screenshot 2023-12-22 at 11 09 30" src="https://github.com/suragch/mongol/assets/10300220/22a1a598-283d-4fa4-b6d7-84cfa02c45fb">

This seems to show that `MongolTextPainter` is not the problem, at least not for the line spacing.

@Satsrag I won't work on this during the weekend so feel free to make any changes. I'll take another look at it next week.

**Comment by Satsrag** [comment]
@suragch Yes, I'll have a try this weekend.

**Comment by Satsrag** [comment]
@suragch, I fixed the issue about doesn't resize larger. But I am not sure that is the right solution. Please have a review [this](https://github.com/suragch/mongol/commit/cd75eadffc88be013f122cde9b3ef88b6984cfbc)

The line spacing, I think we should not solve it. Its performance is similar to the `Text` widget.
![default_line_space](https://github.com/suragch/mongol/assets/17843861/a6328235-e813-47b9-b369-db575f65539a)

After setting the `style: TextStyle(height: 1)`:
![1_height](https://github.com/suragch/mongol/assets/17843861/aa7442d3-d925-40df-82e8-7fe8514ee371)

**Comment by suragch** [comment]
@Satsrag  Thank you for all of your work on this! I've published the package as 7.0.0 now. But I also created issues #48 and #49 to track progress on issues related to this change. 

There were three breaking tests that I "fixed" by adjusting the height numbers. I think two of the breaks were related to #49 since multiline text now defaults to the parent height rather than the longest line height like it was before.
